Feat: Table DB 구현
OOP-PROJ4-TEAM4/TABLE_GENERATOR pull request #5
Opened 2024-12-01 12:59 UTC by acidify04

- Table DB를 구현하였습니다.

2024-12-01 13:14 UTC, jaeho0718 commented on CMakeLists.txt
> +add_executable(${PROJECT_NAME} ${SOURCE_FILES} "include/table.h" "include/table_db.h" "src/table_db/table.cpp" "src/table_db/table_db.cpp")
`add_executable(${PROJECT_NAME} ${SOURCE_FILES})` 에서 빌드시 자동으로 프로젝트내 파일을 링크시키므로, "include/table.h" "include/table_db.h" "src/table_db/table.cpp" "src/table_db/table_db.cpp" 부분은 필요없습니다.

2024-12-01 13:16 UTC, jaeho0718 commented on include/table.h
> +
table_db의 헤더파일에서 Table을 사용하고, 해당 헤더파일에서는 TableQuery를 사용하면,  헤더 순환참조가 발생합니다.
따라서 전방참조를 이용해 문제를 없앨 수 있어요.
``` cpp
struct TableQuery;
```
를 해당 위치에 추가하면 됩니다.

2024-12-01 13:21 UTC, jaeho0718 commented on include/table_db.h
> +
table 헤더파일과 마찬가지로 헤더순환참조 문제가 발생하므로, 전방선언을 이용해 해당 문제를 해결할 수 있습니다.
```cpp
class Table;
```
를 추가하세요.

2024-12-01 13:22 UTC, jaeho0718 commented on include/table_db.h
> +struct TableQuery
TableDatabase class 선언에서 TableQuery 구조체를 사용하는데, TableQuery구조체 선언이 해당 클래스 선언보다 뒤에 있습니다.
해당 구조체가 사용되기전에 선언이 앞서있어야합니다. (즉 TableDatabase 클래스 앞쪽으로 옮겨주세요.)

2024-12-01 13:25 UTC, jaeho0718 commented on src/table_db/table.cpp
> +Table::Table(string &str){
table.h 파일을 보면 `Table::Table(const string& str)`로 선언이 되어있습니다. 이때 파라미터 타입이 일치하지 않으므로 수정이 필요합니다.

2024-12-01 13:27 UTC, jaeho0718 commented on src/table_db/table.cpp
> +struct ParseResult
`ParseResult`와 `ParseResult parse_tag(string::const_iterator&, const string::const_iterator&)` 함수를 직접 선언하지 마시고 `parser.h`헤더파일에 있는 함수를 사용해주세요.

2024-12-01 13:29 UTC, jaeho0718 commented on src/table_db/table.cpp
> +string encode_semester(Semester semester) {
`string encode_semester(Semester semester)` 해당 함수는 `course.h`파일에 있습니다. `course.h`에 있는 함수를 사용하는게 좋을 것 같아요!.
이 외에도 `Course`의 속성과 관련된 인코딩, 디코딩 함수가 모두 `course.h` 파일에 있으므로 참고하세요.

2024-12-01 13:31 UTC, jaeho0718 commented on include/table_db.h
> +};
`semster`과 `department`의 경우 `string` 타입보다는 `course.h`에 있는 `Semester`, `Department` 열거형을 사용하는게 좋을 것 같아요.

2024-12-01 13:33 UTC, jaeho0718 commented on src/table_db/table_db.cpp
> +string encode_semester(Semester semester)
`Course` 의 속성과 관련된 인코딩 함수가 `course.h`에 포함되어있으므로, 해당 함수를 사용해주세요.

2024-12-01 13:41 UTC, jaeho0718 commented on src/table_db/table_db.cpp
> +                ParseResult result = parse_tag(line.begin(), line.end());
첫번째 인자는 `const`가 아니므로 별도 변수를 선언해 넣어줘야합니다.
```cpp
string::const_iterator it = line.begin();
ParseResult result = parse_tag(it, line.end());
```

2024-12-01 13:42 UTC, jaeho0718 commented on src/table_db/table_db.cpp
> +string encode_course_type(CourseType course_type) {
Course 의 속성과 관련된 인코딩 함수가 course.h에 포함되어있으므로, 해당 함수를 사용해주세요.

2024-12-01 13:43 UTC, jaeho0718 commented on tag_parser.cpp
`include/parser.h`부분에 이미 선언되어있으므로, 해당 파일은 지워주세요.

2024-12-01 13:45 UTC, jaeho0718 commented on CMakeLists.txt
`CMakeLists.txt`를  visual studio에서 사용시 파일을 추가하면 자동으로 파일경로가 추가되는데, 이는 중복된 파일경로를 야기할 수 있으므로 **`CMakeLists.txt`은  절대 수정하지 말아주세요.**

2024-12-01 13:46 UTC, jaeho0718 requested changes
변경사항 관련하여 각 코드별 코멘트 달아놓았습니다. 👍

2024-12-02 01:03 UTC, jaeho0718 commented
`Course`와 `CourseDB` 파일 보니깐, 병합시 일부 코드가 뒤섞인거 같은데, 혹시 main 브랜치에 있는 `course.cpp`과  `course_db.cpp`파일 코드를 은효님의 해당 파일 코드에 복붙해서 커밋 해주실 수 있나요?

2024-12-02 02:28 UTC, jaeho0718 commented
@acidify04 라이브러리 임포트 문제 관련하여 수정해서 PR 올려놨습니다. 확인후 해당 커밋을 반영해 다시 빌드해보세요.

2024-12-02 06:15 UTC, YamYamee approved these changes

2024-12-02 06:15 UTC, merged